name: Trigger Repository A

on:
  push:
    branches:
      - main

jobs:
  notify-repoA:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Repository A
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_B_TOKEN }}
        repository: justakazh/docs
        event-type: "repoB-push"
